/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Varaus API
 * API for reserving things
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  OccurrenceCreate,
  OccurrenceRead,
  ReadOccurrencesParams,
  ReadReservationsParams,
  ReservationCreate,
  ReservationRead,
  ReservationUpdate
} from '../../models';





/**
 * @summary Create Reservation
 */
export type createReservationResponse201 = {
  data: ReservationRead
  status: 201
}

export type createReservationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createReservationResponseSuccess = (createReservationResponse201) & {
  headers: Headers;
};
export type createReservationResponseError = (createReservationResponse422) & {
  headers: Headers;
};

export type createReservationResponse = (createReservationResponseSuccess | createReservationResponseError)

export const getCreateReservationUrl = () => {




  return `/api/reservations/reservations/`
}

export const createReservation = async (reservationCreate: ReservationCreate, options?: RequestInit): Promise<createReservationResponse> => {

  const res = await fetch(getCreateReservationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reservationCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createReservationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createReservationResponse
}




export const getCreateReservationMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReservation>>, TError,{data: ReservationCreate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createReservation>>, TError,{data: ReservationCreate}, TContext> => {

const mutationKey = ['createReservation'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReservation>>, {data: ReservationCreate}> = (props) => {
          const {data} = props ?? {};

          return  createReservation(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateReservationMutationResult = NonNullable<Awaited<ReturnType<typeof createReservation>>>
    export type CreateReservationMutationBody = ReservationCreate
    export type CreateReservationMutationError = HTTPValidationError

    /**
 * @summary Create Reservation
 */
export const useCreateReservation = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReservation>>, TError,{data: ReservationCreate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createReservation>>,
        TError,
        {data: ReservationCreate},
        TContext
      > => {
      return useMutation(getCreateReservationMutationOptions(options), queryClient);
    }
    /**
 * @summary Read Reservations
 */
export type readReservationsResponse200 = {
  data: ReservationRead[]
  status: 200
}

export type readReservationsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readReservationsResponseSuccess = (readReservationsResponse200) & {
  headers: Headers;
};
export type readReservationsResponseError = (readReservationsResponse422) & {
  headers: Headers;
};

export type readReservationsResponse = (readReservationsResponseSuccess | readReservationsResponseError)

export const getReadReservationsUrl = (params?: ReadReservationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/reservations/reservations/?${stringifiedParams}` : `/api/reservations/reservations/`
}

export const readReservations = async (params?: ReadReservationsParams, options?: RequestInit): Promise<readReservationsResponse> => {

  const res = await fetch(getReadReservationsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readReservationsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readReservationsResponse
}





export const getReadReservationsQueryKey = (params?: ReadReservationsParams,) => {
    return [
    `/api/reservations/reservations/`, ...(params ? [params] : [])
    ] as const;
    }


export const getReadReservationsQueryOptions = <TData = Awaited<ReturnType<typeof readReservations>>, TError = HTTPValidationError>(params?: ReadReservationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReservations>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadReservationsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readReservations>>> = ({ signal }) => readReservations(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readReservations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadReservationsQueryResult = NonNullable<Awaited<ReturnType<typeof readReservations>>>
export type ReadReservationsQueryError = HTTPValidationError


export function useReadReservations<TData = Awaited<ReturnType<typeof readReservations>>, TError = HTTPValidationError>(
 params: undefined |  ReadReservationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReservations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readReservations>>,
          TError,
          Awaited<ReturnType<typeof readReservations>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadReservations<TData = Awaited<ReturnType<typeof readReservations>>, TError = HTTPValidationError>(
 params?: ReadReservationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReservations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readReservations>>,
          TError,
          Awaited<ReturnType<typeof readReservations>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadReservations<TData = Awaited<ReturnType<typeof readReservations>>, TError = HTTPValidationError>(
 params?: ReadReservationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReservations>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Reservations
 */

export function useReadReservations<TData = Awaited<ReturnType<typeof readReservations>>, TError = HTTPValidationError>(
 params?: ReadReservationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReservations>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadReservationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Read Reservation
 */
export type readReservationResponse200 = {
  data: ReservationRead
  status: 200
}

export type readReservationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readReservationResponseSuccess = (readReservationResponse200) & {
  headers: Headers;
};
export type readReservationResponseError = (readReservationResponse422) & {
  headers: Headers;
};

export type readReservationResponse = (readReservationResponseSuccess | readReservationResponseError)

export const getReadReservationUrl = (reservationId: string,) => {




  return `/api/reservations/reservations/${reservationId}`
}

export const readReservation = async (reservationId: string, options?: RequestInit): Promise<readReservationResponse> => {

  const res = await fetch(getReadReservationUrl(reservationId),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readReservationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readReservationResponse
}





export const getReadReservationQueryKey = (reservationId: string,) => {
    return [
    `/api/reservations/reservations/${reservationId}`
    ] as const;
    }


export const getReadReservationQueryOptions = <TData = Awaited<ReturnType<typeof readReservation>>, TError = HTTPValidationError>(reservationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReservation>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadReservationQueryKey(reservationId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readReservation>>> = ({ signal }) => readReservation(reservationId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(reservationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readReservation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadReservationQueryResult = NonNullable<Awaited<ReturnType<typeof readReservation>>>
export type ReadReservationQueryError = HTTPValidationError


export function useReadReservation<TData = Awaited<ReturnType<typeof readReservation>>, TError = HTTPValidationError>(
 reservationId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReservation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readReservation>>,
          TError,
          Awaited<ReturnType<typeof readReservation>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadReservation<TData = Awaited<ReturnType<typeof readReservation>>, TError = HTTPValidationError>(
 reservationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReservation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readReservation>>,
          TError,
          Awaited<ReturnType<typeof readReservation>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadReservation<TData = Awaited<ReturnType<typeof readReservation>>, TError = HTTPValidationError>(
 reservationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReservation>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Reservation
 */

export function useReadReservation<TData = Awaited<ReturnType<typeof readReservation>>, TError = HTTPValidationError>(
 reservationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readReservation>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadReservationQueryOptions(reservationId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Update Reservation
 */
export type updateReservationResponse200 = {
  data: ReservationRead
  status: 200
}

export type updateReservationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateReservationResponseSuccess = (updateReservationResponse200) & {
  headers: Headers;
};
export type updateReservationResponseError = (updateReservationResponse422) & {
  headers: Headers;
};

export type updateReservationResponse = (updateReservationResponseSuccess | updateReservationResponseError)

export const getUpdateReservationUrl = (reservationId: string,) => {




  return `/api/reservations/reservations/${reservationId}`
}

export const updateReservation = async (reservationId: string,
    reservationUpdate: ReservationUpdate, options?: RequestInit): Promise<updateReservationResponse> => {

  const res = await fetch(getUpdateReservationUrl(reservationId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reservationUpdate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateReservationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateReservationResponse
}




export const getUpdateReservationMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReservation>>, TError,{reservationId: string;data: ReservationUpdate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateReservation>>, TError,{reservationId: string;data: ReservationUpdate}, TContext> => {

const mutationKey = ['updateReservation'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateReservation>>, {reservationId: string;data: ReservationUpdate}> = (props) => {
          const {reservationId,data} = props ?? {};

          return  updateReservation(reservationId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateReservationMutationResult = NonNullable<Awaited<ReturnType<typeof updateReservation>>>
    export type UpdateReservationMutationBody = ReservationUpdate
    export type UpdateReservationMutationError = HTTPValidationError

    /**
 * @summary Update Reservation
 */
export const useUpdateReservation = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReservation>>, TError,{reservationId: string;data: ReservationUpdate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateReservation>>,
        TError,
        {reservationId: string;data: ReservationUpdate},
        TContext
      > => {
      return useMutation(getUpdateReservationMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Reservation
 */
export type deleteReservationResponse204 = {
  data: void
  status: 204
}

export type deleteReservationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteReservationResponseSuccess = (deleteReservationResponse204) & {
  headers: Headers;
};
export type deleteReservationResponseError = (deleteReservationResponse422) & {
  headers: Headers;
};

export type deleteReservationResponse = (deleteReservationResponseSuccess | deleteReservationResponseError)

export const getDeleteReservationUrl = (reservationId: string,) => {




  return `/api/reservations/reservations/${reservationId}`
}

export const deleteReservation = async (reservationId: string, options?: RequestInit): Promise<deleteReservationResponse> => {

  const res = await fetch(getDeleteReservationUrl(reservationId),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteReservationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteReservationResponse
}




export const getDeleteReservationMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReservation>>, TError,{reservationId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteReservation>>, TError,{reservationId: string}, TContext> => {

const mutationKey = ['deleteReservation'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReservation>>, {reservationId: string}> = (props) => {
          const {reservationId} = props ?? {};

          return  deleteReservation(reservationId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteReservationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReservation>>>

    export type DeleteReservationMutationError = HTTPValidationError

    /**
 * @summary Delete Reservation
 */
export const useDeleteReservation = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReservation>>, TError,{reservationId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteReservation>>,
        TError,
        {reservationId: string},
        TContext
      > => {
      return useMutation(getDeleteReservationMutationOptions(options), queryClient);
    }
    /**
 * @summary Create Occurrence
 */
export type createOccurrenceResponse201 = {
  data: OccurrenceRead
  status: 201
}

export type createOccurrenceResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createOccurrenceResponseSuccess = (createOccurrenceResponse201) & {
  headers: Headers;
};
export type createOccurrenceResponseError = (createOccurrenceResponse422) & {
  headers: Headers;
};

export type createOccurrenceResponse = (createOccurrenceResponseSuccess | createOccurrenceResponseError)

export const getCreateOccurrenceUrl = () => {




  return `/api/reservations/occurrences/`
}

export const createOccurrence = async (occurrenceCreate: OccurrenceCreate, options?: RequestInit): Promise<createOccurrenceResponse> => {

  const res = await fetch(getCreateOccurrenceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      occurrenceCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createOccurrenceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createOccurrenceResponse
}




export const getCreateOccurrenceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOccurrence>>, TError,{data: OccurrenceCreate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createOccurrence>>, TError,{data: OccurrenceCreate}, TContext> => {

const mutationKey = ['createOccurrence'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOccurrence>>, {data: OccurrenceCreate}> = (props) => {
          const {data} = props ?? {};

          return  createOccurrence(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateOccurrenceMutationResult = NonNullable<Awaited<ReturnType<typeof createOccurrence>>>
    export type CreateOccurrenceMutationBody = OccurrenceCreate
    export type CreateOccurrenceMutationError = HTTPValidationError

    /**
 * @summary Create Occurrence
 */
export const useCreateOccurrence = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOccurrence>>, TError,{data: OccurrenceCreate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOccurrence>>,
        TError,
        {data: OccurrenceCreate},
        TContext
      > => {
      return useMutation(getCreateOccurrenceMutationOptions(options), queryClient);
    }
    /**
 * @summary Read Occurrences
 */
export type readOccurrencesResponse200 = {
  data: OccurrenceRead[]
  status: 200
}

export type readOccurrencesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readOccurrencesResponseSuccess = (readOccurrencesResponse200) & {
  headers: Headers;
};
export type readOccurrencesResponseError = (readOccurrencesResponse422) & {
  headers: Headers;
};

export type readOccurrencesResponse = (readOccurrencesResponseSuccess | readOccurrencesResponseError)

export const getReadOccurrencesUrl = (params?: ReadOccurrencesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/reservations/occurrences/?${stringifiedParams}` : `/api/reservations/occurrences/`
}

export const readOccurrences = async (params?: ReadOccurrencesParams, options?: RequestInit): Promise<readOccurrencesResponse> => {

  const res = await fetch(getReadOccurrencesUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readOccurrencesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readOccurrencesResponse
}





export const getReadOccurrencesQueryKey = (params?: ReadOccurrencesParams,) => {
    return [
    `/api/reservations/occurrences/`, ...(params ? [params] : [])
    ] as const;
    }


export const getReadOccurrencesQueryOptions = <TData = Awaited<ReturnType<typeof readOccurrences>>, TError = HTTPValidationError>(params?: ReadOccurrencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readOccurrences>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadOccurrencesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readOccurrences>>> = ({ signal }) => readOccurrences(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readOccurrences>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadOccurrencesQueryResult = NonNullable<Awaited<ReturnType<typeof readOccurrences>>>
export type ReadOccurrencesQueryError = HTTPValidationError


export function useReadOccurrences<TData = Awaited<ReturnType<typeof readOccurrences>>, TError = HTTPValidationError>(
 params: undefined |  ReadOccurrencesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readOccurrences>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readOccurrences>>,
          TError,
          Awaited<ReturnType<typeof readOccurrences>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadOccurrences<TData = Awaited<ReturnType<typeof readOccurrences>>, TError = HTTPValidationError>(
 params?: ReadOccurrencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readOccurrences>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readOccurrences>>,
          TError,
          Awaited<ReturnType<typeof readOccurrences>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadOccurrences<TData = Awaited<ReturnType<typeof readOccurrences>>, TError = HTTPValidationError>(
 params?: ReadOccurrencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readOccurrences>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Occurrences
 */

export function useReadOccurrences<TData = Awaited<ReturnType<typeof readOccurrences>>, TError = HTTPValidationError>(
 params?: ReadOccurrencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readOccurrences>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadOccurrencesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Delete Occurrence
 */
export type deleteOccurrenceResponse204 = {
  data: void
  status: 204
}

export type deleteOccurrenceResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteOccurrenceResponseSuccess = (deleteOccurrenceResponse204) & {
  headers: Headers;
};
export type deleteOccurrenceResponseError = (deleteOccurrenceResponse422) & {
  headers: Headers;
};

export type deleteOccurrenceResponse = (deleteOccurrenceResponseSuccess | deleteOccurrenceResponseError)

export const getDeleteOccurrenceUrl = (occurrenceId: string,) => {




  return `/api/reservations/occurrences/${occurrenceId}`
}

export const deleteOccurrence = async (occurrenceId: string, options?: RequestInit): Promise<deleteOccurrenceResponse> => {

  const res = await fetch(getDeleteOccurrenceUrl(occurrenceId),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteOccurrenceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteOccurrenceResponse
}




export const getDeleteOccurrenceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOccurrence>>, TError,{occurrenceId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteOccurrence>>, TError,{occurrenceId: string}, TContext> => {

const mutationKey = ['deleteOccurrence'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOccurrence>>, {occurrenceId: string}> = (props) => {
          const {occurrenceId} = props ?? {};

          return  deleteOccurrence(occurrenceId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteOccurrenceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOccurrence>>>

    export type DeleteOccurrenceMutationError = HTTPValidationError

    /**
 * @summary Delete Occurrence
 */
export const useDeleteOccurrence = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOccurrence>>, TError,{occurrenceId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteOccurrence>>,
        TError,
        {occurrenceId: string},
        TContext
      > => {
      return useMutation(getDeleteOccurrenceMutationOptions(options), queryClient);
    }
