/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Varaus API
 * API for reserving things
 * OpenAPI spec version: 0.0.0
 */
import type { ConflictDetail } from './conflictDetail';

export interface ConflictCheckResponse {
  has_conflicts: boolean;
  conflicts: ConflictDetail[];
}
