/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Varaus API
 * API for reserving things
 * OpenAPI spec version: 0.0.0
 */

export interface ConflictDetail {
  resource_id: string;
  start: string;
  end: string;
  reservation_id: string;
  reservation_name: string;
}
