/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Varaus API
 * API for reserving things
 * OpenAPI spec version: 0.0.0
 */
import type { Interval } from './interval';

export interface ConflictCheckRequest {
  resourceIds: string[];
  intervals: Interval[];
}
