/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Varaus API
 * API for reserving things
 * OpenAPI spec version: 0.0.0
 */

export * from './hTTPValidationError';
export * from './readResourcesParams';
export * from './resourceCreate';
export * from './resourceRead';
export * from './resourceUpdate';
export * from './validationError';
export * from './validationErrorCtx';
