/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Varaus API
 * API for reserving things
 * OpenAPI spec version: 0.0.0
 */

export interface OccurrenceCreate {
  reservation_id: string;
  resource_id: string;
  start_time: string;
  end_time: string;
}
