/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Varaus API
 * API for reserving things
 * OpenAPI spec version: 0.0.0
 */

export type ReadOccurrencesParams = {
start?: string | null;
end?: string | null;
resource_ids?: string[] | null;
offset?: number;
limit?: number;
};
