/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Varaus API
 * API for reserving things
 * OpenAPI spec version: 0.0.0
 */

export type ReadResourcesParams = {
offset?: number;
limit?: number;
};
