/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Varaus API
 * API for reserving things
 * OpenAPI spec version: 0.0.0
 */
import type { ReservationStatus } from './reservationStatus';

export interface ReservationCreate {
  name: string;
  description?: string | null;
  rrule?: string | null;
  status?: ReservationStatus;
}
