/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Varaus API
 * API for reserving things
 * OpenAPI spec version: 0.0.0
 */

export type ReservationStatus = typeof ReservationStatus[keyof typeof ReservationStatus];


export const ReservationStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  cancelled: 'cancelled',
  informative: 'informative',
} as const;
