/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Varaus API
 * API for reserving things
 * OpenAPI spec version: 0.0.0
 */
import type { Interval } from './interval';
import type { ReservationStatus } from './reservationStatus';

export interface ReservationWithOccurrencesCreate {
  name: string;
  description?: string | null;
  rrule?: string | null;
  status?: ReservationStatus;
  resource_ids: string[];
  intervals: Interval[];
}
