/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Varaus API
 * API for reserving things
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  ReadResourcesParams,
  ResourceCreate,
  ResourceRead,
  ResourceUpdate
} from '../../models';





/**
 * @summary Create Resource
 */
export type createResourceResponse201 = {
  data: ResourceRead
  status: 201
}

export type createResourceResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createResourceResponseSuccess = (createResourceResponse201) & {
  headers: Headers;
};
export type createResourceResponseError = (createResourceResponse422) & {
  headers: Headers;
};

export type createResourceResponse = (createResourceResponseSuccess | createResourceResponseError)

export const getCreateResourceUrl = () => {




  return `/api/resources/`
}

export const createResource = async (resourceCreate: ResourceCreate, options?: RequestInit): Promise<createResourceResponse> => {

  const res = await fetch(getCreateResourceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resourceCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createResourceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createResourceResponse
}




export const getCreateResourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createResource>>, TError,{data: ResourceCreate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createResource>>, TError,{data: ResourceCreate}, TContext> => {

const mutationKey = ['createResource'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createResource>>, {data: ResourceCreate}> = (props) => {
          const {data} = props ?? {};

          return  createResource(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateResourceMutationResult = NonNullable<Awaited<ReturnType<typeof createResource>>>
    export type CreateResourceMutationBody = ResourceCreate
    export type CreateResourceMutationError = HTTPValidationError

    /**
 * @summary Create Resource
 */
export const useCreateResource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createResource>>, TError,{data: ResourceCreate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createResource>>,
        TError,
        {data: ResourceCreate},
        TContext
      > => {
      return useMutation(getCreateResourceMutationOptions(options), queryClient);
    }
    /**
 * @summary Read Resources
 */
export type readResourcesResponse200 = {
  data: ResourceRead[]
  status: 200
}

export type readResourcesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readResourcesResponseSuccess = (readResourcesResponse200) & {
  headers: Headers;
};
export type readResourcesResponseError = (readResourcesResponse422) & {
  headers: Headers;
};

export type readResourcesResponse = (readResourcesResponseSuccess | readResourcesResponseError)

export const getReadResourcesUrl = (params?: ReadResourcesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/resources/?${stringifiedParams}` : `/api/resources/`
}

export const readResources = async (params?: ReadResourcesParams, options?: RequestInit): Promise<readResourcesResponse> => {

  const res = await fetch(getReadResourcesUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readResourcesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readResourcesResponse
}





export const getReadResourcesQueryKey = (params?: ReadResourcesParams,) => {
    return [
    `/api/resources/`, ...(params ? [params] : [])
    ] as const;
    }


export const getReadResourcesQueryOptions = <TData = Awaited<ReturnType<typeof readResources>>, TError = HTTPValidationError>(params?: ReadResourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readResources>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadResourcesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readResources>>> = ({ signal }) => readResources(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readResources>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadResourcesQueryResult = NonNullable<Awaited<ReturnType<typeof readResources>>>
export type ReadResourcesQueryError = HTTPValidationError


export function useReadResources<TData = Awaited<ReturnType<typeof readResources>>, TError = HTTPValidationError>(
 params: undefined |  ReadResourcesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readResources>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readResources>>,
          TError,
          Awaited<ReturnType<typeof readResources>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadResources<TData = Awaited<ReturnType<typeof readResources>>, TError = HTTPValidationError>(
 params?: ReadResourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readResources>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readResources>>,
          TError,
          Awaited<ReturnType<typeof readResources>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadResources<TData = Awaited<ReturnType<typeof readResources>>, TError = HTTPValidationError>(
 params?: ReadResourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readResources>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Resources
 */

export function useReadResources<TData = Awaited<ReturnType<typeof readResources>>, TError = HTTPValidationError>(
 params?: ReadResourcesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readResources>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadResourcesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Read Resource
 */
export type readResourceResponse200 = {
  data: ResourceRead
  status: 200
}

export type readResourceResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readResourceResponseSuccess = (readResourceResponse200) & {
  headers: Headers;
};
export type readResourceResponseError = (readResourceResponse422) & {
  headers: Headers;
};

export type readResourceResponse = (readResourceResponseSuccess | readResourceResponseError)

export const getReadResourceUrl = (resourceId: string,) => {




  return `/api/resources/${resourceId}`
}

export const readResource = async (resourceId: string, options?: RequestInit): Promise<readResourceResponse> => {

  const res = await fetch(getReadResourceUrl(resourceId),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readResourceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readResourceResponse
}





export const getReadResourceQueryKey = (resourceId: string,) => {
    return [
    `/api/resources/${resourceId}`
    ] as const;
    }


export const getReadResourceQueryOptions = <TData = Awaited<ReturnType<typeof readResource>>, TError = HTTPValidationError>(resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readResource>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadResourceQueryKey(resourceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readResource>>> = ({ signal }) => readResource(resourceId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: !!(resourceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readResource>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadResourceQueryResult = NonNullable<Awaited<ReturnType<typeof readResource>>>
export type ReadResourceQueryError = HTTPValidationError


export function useReadResource<TData = Awaited<ReturnType<typeof readResource>>, TError = HTTPValidationError>(
 resourceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readResource>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readResource>>,
          TError,
          Awaited<ReturnType<typeof readResource>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadResource<TData = Awaited<ReturnType<typeof readResource>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readResource>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readResource>>,
          TError,
          Awaited<ReturnType<typeof readResource>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadResource<TData = Awaited<ReturnType<typeof readResource>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readResource>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Resource
 */

export function useReadResource<TData = Awaited<ReturnType<typeof readResource>>, TError = HTTPValidationError>(
 resourceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readResource>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadResourceQueryOptions(resourceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Update Resource
 */
export type updateResourceResponse200 = {
  data: ResourceRead
  status: 200
}

export type updateResourceResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateResourceResponseSuccess = (updateResourceResponse200) & {
  headers: Headers;
};
export type updateResourceResponseError = (updateResourceResponse422) & {
  headers: Headers;
};

export type updateResourceResponse = (updateResourceResponseSuccess | updateResourceResponseError)

export const getUpdateResourceUrl = (resourceId: string,) => {




  return `/api/resources/${resourceId}`
}

export const updateResource = async (resourceId: string,
    resourceUpdate: ResourceUpdate, options?: RequestInit): Promise<updateResourceResponse> => {

  const res = await fetch(getUpdateResourceUrl(resourceId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resourceUpdate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateResourceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateResourceResponse
}




export const getUpdateResourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateResource>>, TError,{resourceId: string;data: ResourceUpdate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateResource>>, TError,{resourceId: string;data: ResourceUpdate}, TContext> => {

const mutationKey = ['updateResource'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateResource>>, {resourceId: string;data: ResourceUpdate}> = (props) => {
          const {resourceId,data} = props ?? {};

          return  updateResource(resourceId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateResourceMutationResult = NonNullable<Awaited<ReturnType<typeof updateResource>>>
    export type UpdateResourceMutationBody = ResourceUpdate
    export type UpdateResourceMutationError = HTTPValidationError

    /**
 * @summary Update Resource
 */
export const useUpdateResource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateResource>>, TError,{resourceId: string;data: ResourceUpdate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateResource>>,
        TError,
        {resourceId: string;data: ResourceUpdate},
        TContext
      > => {
      return useMutation(getUpdateResourceMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Resource
 */
export type deleteResourceResponse204 = {
  data: void
  status: 204
}

export type deleteResourceResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteResourceResponseSuccess = (deleteResourceResponse204) & {
  headers: Headers;
};
export type deleteResourceResponseError = (deleteResourceResponse422) & {
  headers: Headers;
};

export type deleteResourceResponse = (deleteResourceResponseSuccess | deleteResourceResponseError)

export const getDeleteResourceUrl = (resourceId: string,) => {




  return `/api/resources/${resourceId}`
}

export const deleteResource = async (resourceId: string, options?: RequestInit): Promise<deleteResourceResponse> => {

  const res = await fetch(getDeleteResourceUrl(resourceId),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteResourceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteResourceResponse
}




export const getDeleteResourceMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteResource>>, TError,{resourceId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteResource>>, TError,{resourceId: string}, TContext> => {

const mutationKey = ['deleteResource'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteResource>>, {resourceId: string}> = (props) => {
          const {resourceId} = props ?? {};

          return  deleteResource(resourceId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteResourceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteResource>>>

    export type DeleteResourceMutationError = HTTPValidationError

    /**
 * @summary Delete Resource
 */
export const useDeleteResource = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteResource>>, TError,{resourceId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteResource>>,
        TError,
        {resourceId: string},
        TContext
      > => {
      return useMutation(getDeleteResourceMutationOptions(options), queryClient);
    }
